from enum import Enum


class ActivityType(Enum):
    LOGIN = "login"
    NEW_DEVICE_LOGIN = "new-device-login"
    NEW_ADDRESS_BOOK_RECORD = "new-address-book-record"
    UPDATE_ADDRESS_BOOK_RECORD = "update-address-book-record"
    DELETE_ADDRESS_BOOK_RECORD = "delete-address-book-record"
    WORKSPACE_CREATION = "workspace-creation"
    WORKSPACE_SETTINGS_APPROVAL_UPDATE = "workspace-settings-approval-update"
    WORKSPACE_NAME_CHANGE = "workspace-name-change"
    WORKSPACE_TAG_CHANGE = "workspace-tag-change"
    TAG_RELINKED = "tag-relinked"
    TAG_AUTO_RELINKED = "tag-auto-relinked"
    TAG_DEACTIVATED = "tag-deactivated"
    ONLY_ADDRESS_BOOK_WITHDRAWALS_SETTINGS_UPDATE = "only-address-book-withdrawals-settings-update"
    TRANSACTION_APPROVAL_SETTINGS_UPDATE = "transaction-approval-settings-update"
    WORKSPACE_MEMBERS_APPROVAL_UPDATE = "workspace-members-approval-update"
    ADDRESS_BOOK_SETTINGS_APPROVAL_UPDATE = "address-book-settings-approval-update"
    TRANSACTION_LIMITS_APPROVAL_SETTINGS_UPDATE = "transaction-limits-approval-settings-update"
    MEMBER_CREATION = "member-creation"
    MEMBER_UPDATE = "member-update"
    SERVICE_MEMBER_CREATION = "service-member-creation"
    TRANSACTION_LIMIT_CREATION = "transaction-limit-creation"
    TRANSACTION_LIMIT_UPDATE = "transaction-limit-update"
    ACCOUNT_CREATION = "account-creation"
    PASSKEY_CREATION = "passkey-creation"
    PASSKEY_DELETION = "passkey-deletion"
    TYPE_2FA_CHANGE = "2fa-change"
    ACCOUNT_PINS_RESET = "account-pins-reset"
    SHARD_ACCESS_REQUEST_UPDATED = "shard-access-request-updated"
    TRANSACTION_COMPLETED = "transaction-completed"
    SUBSCRIPTION_UPDATED = "subscription-updated"
    TRIAL_PROLONGATION_REQUESTED = "trial-prolongation-requested"
    TRIAL_PROLONGATED = "trial-prolongated"
    OWNERSHIP_TAKEOVER_REQUEST_CREATED = "ownership-takeover-request-created"
    OWNERSHIP_TAKEOVER_REQUEST_CANCELLED = "ownership-takeover-request-cancelled"
    OWNERSHIP_TAKEOVER_NEW_BENEFICIARY_ADDED = "ownership-takeover-new-beneficiary-added"
    OWNERSHIP_TAKEOVER_BENEFICIARY_LEFT = "ownership-takeover-beneficiary-left"
    OWNERSHIP_TAKEOVER_REQUEST_COMPLETED = "ownership-takeover-request-completed"
