from enum import Enum


class EventType(Enum):
    IN = "in"
    OUT = "out"
    FEE = "fee"
    NEGATIVE_DEPOSIT = "negative-deposit"
    STAKE_DEPOSIT = "stake-deposit"
    STAKE_DELEGATION = "stake-delegation"
    STAKE_UNDELEGATION = "stake-undelegation"
    STAKE_WITHDRAWN = "stake-withdrawn"
    STAKE_EARN_REWARD = "stake-earn-reward"
    STAKE_REWARD_ACCRUED = "stake-reward-accrued"
    STAKE_POOL_CREATED = "stake-pool-created"
    STAKE_POOL_UNJAILED = "stake-pool-unjailed"
    STAKE_TRANSFERRED = "stake-transferred"
    ALLOWANCE = "allowance"
    NFT_IN = "nft-in"
    NFT_OUT = "nft-out"
    NFT_ALLOWANCE = "nft-allowance"
    LOYALTY_LOCK = "loyalty-lock"
    LOYALTY_UNLOCK = "loyalty-unlock"
    LOYALTY_REWARD = "loyalty-reward"
    CANTON_REWARD = "canton-reward"
    MESSAGE_SIGNED = "message-signed"
    DEPOSIT_OFFER = "deposit-offer"
