from __future__ import annotations
from typing import Any, Dict, List, Optional, TypedDict

class GetTransactionsQuery(TypedDict, total=False):
    transactionIds: Optional[List[str]]
    transactionTypes: Optional[List[TransactionType]]
    accountTypes: Optional[List[AccountType]]
    accountId: Optional[str]
    accountIds: Optional[List[str]]
    transactionStatuses: Optional[List[TransactionStatus]]
    transactionStatusNotIn: Optional[List[TransactionStatus]]
    assetIds: Optional[List[str]]
    blockchainTxId: Optional[str]
    toAccountId: Optional[str]
    toAddress: Optional[str]
    isTerminated: Optional[bool]
    terminatedAtFrom: Optional[str]
    terminatedAtTo: Optional[str]
    createdAtFrom: Optional[str]
    createdAtTo: Optional[str]
    updatedAtFrom: Optional[str]
    updatedAtTo: Optional[str]
    canSignWithDeviceId: Optional[str]
    sortBy: Optional[SortBy]
    sortDirection: Optional[SortingDirection]
    limit: Optional[str]
    offset: Optional[str]
    externalId: Optional[str]
    includeEvents: Optional[bool]
    includeCurrentSigningRequest: Optional[bool]
