from enum import Enum


class activity_type(Enum):
    LOGIN = "login"
    NEW_DEVICE_LOGIN = "new-device-login"
    NEW_ADDRESS_BOOK_RECORD = "new-address-book-record"
    UPDATE_ADDRESS_BOOK_RECORD = "update-address-book-record"
    DELETE_ADDRESS_BOOK_RECORD = "delete-address-book-record"
    WORKSPACE_CREATION = "workspace-creation"
    WORKSPACE_SETTINGS_APPROVAL_UPDATE = "workspace-settings-approval-update"
    WORKSPACE_NAME_CHANGE = "workspace-name-change"
    WORKSPACE_TAG_CHANGE = "workspace-tag-change"
    ONLY_ADDRESS_BOOK_WITHDRAWALS_SETTINGS_UPDATE = "only-address-book-withdrawals-settings-update"
    TRANSACTION_APPROVAL_SETTINGS_UPDATE = "transaction-approval-settings-update"
    WORKSPACE_MEMBERS_APPROVAL_UPDATE = "workspace-members-approval-update"
    ADDRESS_BOOK_SETTINGS_APPROVAL_UPDATE = "address-book-settings-approval-update"
    TRANSACTION_LIMITS_APPROVAL_SETTINGS_UPDATE = "transaction-limits-approval-settings-update"
    MEMBER_CREATION = "member-creation"
    SERVICE_MEMBER_CREATION = "service-member-creation"
    TRANSACTION_LIMIT_CREATION = "transaction-limit-creation"
    TRANSACTION_LIMIT_UPDATE = "transaction-limit-update"
    ACCOUNT_CREATION = "account-creation"
    PASSKEY_CREATION = "passkey-creation"
    PASSKEY_DELETION = "passkey-deletion"
    TYPE_2FA_CHANGE = "2fa-change"
    ACCOUNT_PINS_RESET = "account-pins-reset"
    SHARD_ACCESS_REQUEST_CREATED = "shard-access-request-created"
    SHARD_ACCESS_REQUEST_FINISHED = "shard-access-request-finished"
    TRANSACTION_COMPLETED = "transaction-completed"
